### PR TITLE
Splay and chunks

### PR DESCRIPTION
**Pull request by vpicaver**

### CODE REVIEW

**Comment by jedwards1211** [comment]
btw is there really such a thing as a "splay shot" in diving?  I would have thought if divers go to the trouble of swimming to a station to get the depth measurement, they'd go ahead and give the station a name

**Comment by jedwards1211** [comment]
Also I thought this PR had chunks, apparently I'm hallucinating :P

**Comment by vpicaver** [comment]
I think I might have closed this because it pushed it up wrong. GitHub is a
bit different than Gerrit that use for work. I think what we have in the
master is good. I think.

I don't think diver do splay shots. Hell they can barely get the centerline
in the book.

Philip

On Wednesday, January 27, 2016, Andy Edwards notifications@github.com
wrote:

> Also I thought this PR had chunks, apparently I'm hallucinating :P
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jedwards1211/metacave/pull/9#issuecomment-175796273.

## 

Phi|ip

Sent from Gmail Mobile

**Comment by vpicaver** [comment]
Weird the chunks didn't make it in...

On Wednesday, January 27, 2016, Philip Schuchardt vpicaver@gmail.com
wrote:

> I think I might have closed this because it pushed it up wrong. GitHub is
> a bit different than Gerrit that use for work. I think what we have in the
> master is good. I think.
> 
> I don't think diver do splay shots. Hell they can barely get the
> centerline in the book.
> 
> Philip
> 
> On Wednesday, January 27, 2016, Andy Edwards <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Also I thought this PR had chunks, apparently I'm hallucinating :P
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jedwards1211/metacave/pull/9#issuecomment-175796273.
> 
> ## 
> 
> Phi|ip
> 
> Sent from Gmail Mobile

## 

Phi|ip

Sent from Gmail Mobile

**Comment by vpicaver** [comment]
Once I get home I can try to push up a new pull request. Currently heading
up to Maine.

Philip

On Wednesday, January 27, 2016, Philip Schuchardt vpicaver@gmail.com
wrote:

> Weird the chunks didn't make it in...
> 
> On Wednesday, January 27, 2016, Philip Schuchardt <vpicaver@gmail.com
> <javascript:_e(%7B%7D,'cvml','vpicaver@gmail.com');>> wrote:
> 
> > I think I might have closed this because it pushed it up wrong. GitHub is
> > a bit different than Gerrit that use for work. I think what we have in the
> > master is good. I think.
> > 
> > I don't think diver do splay shots. Hell they can barely get the
> > centerline in the book.
> > 
> > Philip
> > 
> > On Wednesday, January 27, 2016, Andy Edwards notifications@github.com
> > wrote:
> > 
> > > Also I thought this PR had chunks, apparently I'm hallucinating :P
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/jedwards1211/metacave/pull/9#issuecomment-175796273
> > > .
> > 
> > ## 
> > 
> > Phi|ip
> > 
> > Sent from Gmail Mobile
> 
> ## 
> 
> Phi|ip
> 
> Sent from Gmail Mobile

## 

Phi|ip

Sent from Gmail Mobile

**Comment by vpicaver** [comment]
Or you can add it in if you have the time.

On Wednesday, January 27, 2016, Philip Schuchardt vpicaver@gmail.com
wrote:

> Once I get home I can try to push up a new pull request. Currently heading
> up to Maine.
> 
> Philip
> 
> On Wednesday, January 27, 2016, Philip Schuchardt <vpicaver@gmail.com
> <javascript:_e(%7B%7D,'cvml','vpicaver@gmail.com');>> wrote:
> 
> > Weird the chunks didn't make it in...
> > 
> > On Wednesday, January 27, 2016, Philip Schuchardt vpicaver@gmail.com
> > wrote:
> > 
> > > I think I might have closed this because it pushed it up wrong. GitHub
> > > is a bit different than Gerrit that use for work. I think what we have in
> > > the master is good. I think.
> > > 
> > > I don't think diver do splay shots. Hell they can barely get the
> > > centerline in the book.
> > > 
> > > Philip
> > > 
> > > On Wednesday, January 27, 2016, Andy Edwards notifications@github.com
> > > wrote:
> > > 
> > > > Also I thought this PR had chunks, apparently I'm hallucinating :P
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/jedwards1211/metacave/pull/9#issuecomment-175796273
> > > > .
> > > 
> > > ## 
> > > 
> > > Phi|ip
> > > 
> > > Sent from Gmail Mobile
> > 
> > ## 
> > 
> > Phi|ip
> > 
> > Sent from Gmail Mobile
> 
> ## 
> 
> Phi|ip
> 
> Sent from Gmail Mobile

## 

Phi|ip

Sent from Gmail Mobile

**Comment by jedwards1211** [comment]
Do you mind if we call them "traverses" instead of "chunks"?  I think traverse is a fairly common term for a string of stations (http://speleogenesis-info.isth.info/directory/glossary/?term=traverse, also Walls uses that term)

**Comment by vpicaver** [comment]
Sounds good, traverses is a way better word than chunks.

On Wednesday, January 27, 2016, Andy Edwards notifications@github.com
wrote:

> Do you mind if we call them "traverses" instead of "chunks"? I think
> traverse is a fairly common term for a string of stations (
> http://speleogenesis-info.isth.info/directory/glossary/?term=traverse,
> also Walls uses that term)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jedwards1211/metacave/pull/9#issuecomment-175812958.

## 

Phi|ip

Sent from Gmail Mobile

**Comment by jedwards1211** [comment]
Oh hmmm.  Which would you prefer?

```
"trips": [
  {
    "survey": {
      "traverses": [
        ...
      ]
    }
  }
]
```

```
"trips": [
  {
    "traverses": [
      ...
    ]
  }
]
```

```
"trips": [
  {
    "survey": [
      [         // first traverse, but the word isn't used in the JSON
        ...
      ],
      ...
    ]
  }
]
```

**Comment by jedwards1211** [comment]
And no pressure to respond soon btw.  Have a good time in Maine!

**Comment by vpicaver** [comment]
I like option #2.

On Wednesday, January 27, 2016, Andy Edwards notifications@github.com
wrote:

> And no pressure to respond soon btw. Have a good time in Maine!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jedwards1211/metacave/pull/9#issuecomment-175821397.

## 

Phi|ip

Sent from Gmail Mobile

**Comment by jedwards1211** [comment]
sounds good to me

**Pull request closed without merging**
