### PR TITLE
Fix for Issue #7 - Support for multiple shot, between two stations

### PR DESCRIPTION
**Pull request by vpicaver**
Tell me what you think. I think this is a good way of doing it. I'm going to have to change how cwSurveyChunk handles data but I think it's a feature that needs to be supported. More and more people are using distox's. It would be nice to download and modify it after the trip. It would save some typing and transcription issues.

### CODE REVIEW

**Comment by jedwards1211** [comment]
Hmmm.  I'm a little wary of it but it seems like probably a good idea.  I kind of liked the idea of keeping the structure very similar to survey sheets, but on the other hand, if there were multiple shots between the same stations written on a survey sheet, it wouldn't be clear if they should be averaged or only one should be used.

Do you imagine any problem with just using `frontsights: []` and `backsights: []` arrays instead of `measurements: []` with `dir` properties, to save space?

**Comment by jedwards1211** [comment]
Also I am tempted to break a trip up into chunks, like you have in Cavewhere, because the way of specifying the breaks in Metacave is currently a bit awkward.

**Comment by vpicaver** [comment]
I think the structure will still be similar to the a sheet of paper. The
one problem I see with using frontsights: [] and backsights: [] is
that it _doesn't
maintain order of entry._ For example, if I have some data that was entered
backwards on the paper, backsights thes fronsights. If we use backsights:
[] and frontsights: [] when you save / load the file, the users data entry
will be flipped and will no longer match what they entered. The current
format doesn't support that as well. We could make the "dir:" options "fs"
and "bs", it would save a little more space. The goal is to also the user
to enter that data into the computer as-is.

I'm also a little wary of the change, but I don't see any way of supporting
multiple shots entry from the distox. DistoX are getting very popular and I
want to implement a method for quick downloading of the data, as well as,
support other distox data formats.

Breaking the trip into chunks would definitely save me some work. We'll
have to think about how to handle splay shots. We could have something like:

chunks: [
     [
           { .... Station .... }
           { .... Shot .... }
           { .... Station .... }
     ],

```
 [
       { .... Station .... }
       { .... Shot .... }
       { .... Station .... }
 ],
```

]

splays: [
      a1: [
            { ... Shot ... },
            { ... Shot ... },
            { ... Shot ... }
      ],
      a2: [
            { ... Shot ... },
            { ... Shot ... },
      ]
]

**Comment by jedwards1211** [comment]
That’s true about shot order...

You know, that structure for splay shots wouldn’t preserve order either.  On survey sheets there’s usually just some note about it being a splay in the to station box.  So we could just have the splay shots in the chunks with one of the stations being {splay: true}.  I think preserving the original order would probably be more important for people going back over handwritten notes looking for blunders than people dealing with imported digitial DistoX data, which should always be 100% true to the original.  Are there times when one needs to consider what order redundant DistoX shots were taken in?

**Comment by vpicaver** [comment]
Splay shots in survey sheets are currently supported already. All you have
to do is exclude the shot distance. I don't think we need {splay: true} in
the station object if we keeping the exclude distance.

I'm trying to support splay shots collected from the distox. Usually
there's a boatload of splays from a single station. When importing the
distox data, it would be nice to just see the centerline data on one page
and the splay data in a separate page.

We could have the following structure as shown below: Where the { splays: [
... shots ... ]
chunks: [
     [
           { .... Station ....
               splays: [
                   { .... Shot .... }
                   { .... Shot .... }
           }
           { .... Shot .... }
           { .... Station .... }
     ],

```
 [
       { .... Station .... }
       { .... Shot .... }
       { .... Station .... }
 ],
```

]

What do you think?

Phi|ip

**Comment by vpicaver** [comment]
I've uploaded another patch that contains the changes I'm proposing.

**Comment by vpicaver** [comment]
Have you had time to look at this change?

**Comment by jedwards1211** [comment]
Sorry, I keep getting busy...

Does one have to name the to stations of splay shots?  In other formats like Walls for instance you can just omit the station name and it gets treated as a splay.  Also how will the splay shots look in the survey editor?  My concern is that we can't ensure that they occur in the same order as they do in paper notes if we put them in separate fields.

It seems to me that these features would be convenient for dealing with DistoX data, but not convenient for working with paper data -- and to me paper data should be a priority in the sense that with DistoX data you can import it and forget about it, trusting that it imported correctly, but data typed in from paper notes might need several rounds of checking for blunders, so the UI should match the paper notes as much as possible if that workflow is to be optimized.  I know the winds are changing away from paper notes...but there's still a lot of historical data people have to work with.

Also, even the raw data from the disto has a linear order that shots and splay shots were taken in, right?

**Comment by vpicaver** [comment]
I completely agree the editor should look exactly like what's on paper.

There's two options for representing splays:
1. Excluding the distance for a shot. There are still station names for
both ends of the splay. This is usually how I enter the data from paper
notes. If you has multiple splays from single station, there would be a
chunk for each splay shot. Usually this method works well for a single
splay. It also cause a new chunk to be created, just like the book.
Cavewhere currently supports this.
1. Radial splays. A series of splay shots taken froma single  station. I
   personally have never done this in a book. Have you? Do you have any
   example notes? Do you do a tree like structure? This would allow for distox
   import.

I'm not sure if you looked at the current change? The splay shots are now
order dependent, order matters. I'll also try to sketch out a
editor interface for the radial splays and upload it to this thread.

Thanks!

On Wednesday, January 20, 2016, Andy Edwards notifications@github.com
wrote:

> Sorry, I keep getting busy...
> 
> Does one have to name the to stations of splay shots? In other formats
> like Walls for instance you can just omit the station name and it gets
> treated as a splay. Also how will the splay shots look in the survey
> editor? My concern is that we can't ensure that they occur in the same
> order as they do in paper notes if we put them in separate fields.
> 
> It seems to me that these features would be convenient for dealing with
> DistoX data, but not convenient for working with paper data -- and to me
> paper data should be a priority in the sense that with DistoX data you can
> import it and forget about it, trusting that it imported correctly, but
> data typed in from paper notes might need several rounds of checking for
> blunders, so the UI should match the paper notes as much as possible if
> that workflow is to be optimized. I know the winds are changing away from
> paper notes...but there's still a lot of historical data people have to
> work with.
> 
> Also, even the raw data from the disto has a linear order that shots and
> splay shots were taken in, right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jedwards1211/metacave/pull/8#issuecomment-173330579.

## 

Phi|ip

Sent from Gmail Mobile

**Comment by jedwards1211** [comment]
I'm thinking about the case where for whatever reason, someone surveys A1 through A5, then later takes splays from A1.  Obviously we wouldn't want to attach them to the A1 station that's part of the A1-A2 shot, because then they would appear before the A1-A2 shot, rather than after the A4-A5 shot.  I suppose we could have an A1 station in a chunk of its own at the end with the splays though.

However, wouldn't it simplify the logic in our programs if the data if splay shots are just like normal shots with the distance excluded and (optionally) no to station name (so that the user doesn't have to think of one or pollute the station namespace)?  It shouldn't be difficult to import DistoX data into that form, should it?

**Comment by jedwards1211** [comment]
In Terlingua Sinkhole Sean and I took what were like radial splay shots, but that didn't necessitate any kind of tree structure.  I think what you mean is taking a splay from one station and then taking another splay from that splay's target?  Which would necessitate a tree structure, but in that case we just choose a first-class station name, because it would get too confusing otherwise (and first-class stations/shots form a tree structure anyway).  And we can of course exclude the distance, though it doesn't have much meaning to begin with in a sinkhole without side passages.

**Comment by jedwards1211** [comment]
Okay, I guess the splays inside the stations could work fine.  I'm sorry, it's been a rough year, I guess I'm resistant to changes like this because I feel stressed about it...

**Comment by jedwards1211** [comment]
As far as radial splays though, you realize if there's a separate editor interface for that, it will look different than what's on paper notes, right?  On paper notes you just have to repeat the from station after each splay shot, typically you split the station box in two to save space, like this:

photo on 1-23-16 at 11 18 am

**Comment by vpicaver** [comment]
No worries! Cavewhere should be a distress project, with no deadlines. :D

I'm just happy we're having a constructive conversation. Email and cheap.
Changing the format later down the line, once we have people using it, will
be much harder.

Let me get the UI sketches up, to make sure we're on the same page.

**Comment by vpicaver** [comment]
Yea, that's pretty much what I want to do with the interface!  After I eat
lunch, I'll send the sketch.

Phi|ip

**Comment by vpicaver** [comment]
screen shot 2016-01-23 at 1 11 21 pm

**Comment by vpicaver** [comment]
You're totally right, after making the sketch, I realized putting the splay[] data in the station is a terrible idea. Using splay[] in the station, we would have to have a special mechanism to get the editor into a "splay mode". This special "splay mode" would had unnecessary complexity as you mentioned in previous email. Perhaps having consecutive stations names in a chunk would implicitly designate the shot as a splay?  We would have to document implicit splay that behaviour in the format. What do you think? Or should we still explicitly label the shot as a splay?

**Comment by vpicaver** [comment]
I think it might be useful to hide / show splay data, when importing disto-x data.

**Comment by jedwards1211** [comment]
I do like the idea of being able to collapse the splay shots, and yeah, it's just a question of what's most convenient to work with.  But of course the data format doesn't have to match Cavewhere's internal implementation (and it shouldn't necessarily in all cases).  Having the splay[] data in the stations in the JSON would be more self-explanatory than anything else I can think of.  And I don't imagine it would be much work to serialize/deserialize from however we end up modeling the data in Cavewhere code.  I'd imagine if we try to make the Cavewhere model depend on matching the JSON structure exactly, it would be less flexible in the long run, right?

I like the idea of consecutive same stations being marked as splays, as well as allowing the user to enter measurements when the next station is blank, and still show "splay" in that blank box.

**Comment by vpicaver** [comment]
Yea, the JSON data doesn't need to match the Cavewhere code exactly.
splays[] work for me as long as they don't need double backsight. Currently
this change doesn't include a way to allow double readings of frontsight /
backsight for the same splay shot. I don't think there's a use case for
having double readings for a single splay shot. I would probably just store
the splay shots in the chunk directly inside of cavewhere. This way the
model / view will stay the same. Do you see any problems with change?

Phi|ip

**Comment by jedwards1211** [comment]
Yeah I've never heard of multiple readings for a splay shot.  If we have to import that from some other format...whatever, we can import it as two "separate" splay shots.  Storing the shots directly inside the chunk sounds good to me!

**Comment by jedwards1211** [comment]
By the way, I didn't notice until merging that you allowed the dist/azm/inc to be optional.  I'd prefer if we require them, and don't let the user enter an information for shots with "missing" measurements.  It seems useless to the program; if they want the program to use a shot, they should get full data for it.  This also would guard against accidental omission of those properties.

**Comment by jedwards1211** [comment]
I understand you may want Cavewhere to save incomplete shots the user has entered...eh...kind of an awkward situation...this is intended as a data interchange format, which like other formats, should only contain complete shots.  Possibly we could store incomplete shot measurements as metadata...we might need to use text for the measurements anyway...

**Comment by vpicaver** [comment]
Here's my thoughts on having distance, azimuth, clino optional:
1. The inclination needs to be optional to support dive data.
2. Azimuth needs to be optional if inclination is "up" or "down".
3. The distance, inclination, and azimuth needs to be optional for LRUD
   connection feature that's in there (of course you just omit all
   measurement).
4. Also being able to store incomplete data would be nice for load / save
   if someone note quite done with typing everything in. This would also allow
   for auto-saving and restoration. Cavewhere and others should be responsible
   for reporting if the data is good or not.

The format allows you from entering chunks that aren't connected. In this
situation, the file is invalid.

Phi|ip

**Comment by jedwards1211** [comment]
Hmmm.  I guess let's say that values can be omitted, but if anyone else uses the format, they shouldn't assume missing inclination means it's 0 for example, but rather that the shot is incomplete and shouldn't go into loop closure.
What are you calling LRUD connection feature?

**Comment by vpicaver** [comment]
Search for 'dist: "auto"' for details about LRUD connection feature.

**Comment by vpicaver** [comment]
The current doc, that was just merged, says "If omitted, means the data is
missing". I guess reading that I would assume that it doesn't exist and
shouldn't treated as zero. Did you understand it as something else. Do we
need to change the wording of the doc?

Phi|ip

**Comment by jedwards1211** [comment]
Oh, well it’s well written, it’s just that several other formats assume zero inclination if it’s omitted, especially since inclinations were less common in bygone eras.  So I’ll just add a bit more text to make it clear

**Pull request merged**
